/*


 */
package sesion17;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tl
 */
public class AdministradorPersonajes extends javax.swing.JFrame {

    private ArrayList<Personaje> personajes = new ArrayList<>();
    private ArrayList<Creador> creadores = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdministradorPersonajes.class.getName());

    /**
     * Creates new form AdministradorPersonajes
     */
    public AdministradorPersonajes() {
        initComponents();
        cargarInfoInicial();

    }

    private void cargarInfoInicial() {
        cbTipoPersonaje.setModel(new DefaultComboBoxModel<TipoPersonaje>(TipoPersonaje.values()));
        cbTipoElemento.setModel(new DefaultComboBoxModel<Elemento>(Elemento.values()));
        cbCreadores.addItem(new Creador("Selecciona", "un creador"));
        txtIdCreador.setText(String.valueOf(Creador.getSiguienteId()));

    }

    private String buscarCreador(int id) {

        for (Creador c : creadores) {
            if (c.getIdCreador() == id) {
                return c.toString();
            }
        }

        return "Desconocido";
    }

    private void cargarPersonajes() {

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0); // 🔥 limpia la tabla

        for (Personaje p : personajes) {

            modelo.addRow(new Object[]{
                p.getNombre(),
                p.getApodo(),
                p.getElemento(),
                p.getTipo(),
                buscarCreador(p.getIdCreador())
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelFormulario = new javax.swing.JPanel();
        panelDetallePersonaje = new javax.swing.JPanel();
        lblTituloPersonajeDetalle = new javax.swing.JLabel();
        lblNombrePersonaje = new javax.swing.JLabel();
        txtNombrePersonaje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtApodoPersonaje = new javax.swing.JTextField();
        cbTipoElemento = new javax.swing.JComboBox<>();
        cbTipoPersonaje = new javax.swing.JComboBox<>();
        cbCreadores = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAddPersonaje = new javax.swing.JButton();
        panelDetalleCreador = new javax.swing.JPanel();
        lblTituloPersonajeDetalle1 = new javax.swing.JLabel();
        lblNombrePersonaje1 = new javax.swing.JLabel();
        txtNombreCreador = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtApellidosCreador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtIdCreador = new javax.swing.JTextField();
        btnAddCreador = new javax.swing.JButton();
        scrollPanelListaPersonajes = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelFormulario.setOpaque(false);
        panelFormulario.setLayout(new java.awt.GridLayout(1, 2));

        panelDetallePersonaje.setBackground(new java.awt.Color(102, 102, 102));
        panelDetallePersonaje.setPreferredSize(new java.awt.Dimension(527, 100));
        java.awt.GridBagLayout panelDetallesCreadorLayout = new java.awt.GridBagLayout();
        panelDetallesCreadorLayout.columnWidths = new int[] {50, 50};
        panelDetallePersonaje.setLayout(panelDetallesCreadorLayout);

        lblTituloPersonajeDetalle.setBackground(new java.awt.Color(51, 0, 204));
        lblTituloPersonajeDetalle.setFont(new java.awt.Font("Yu Gothic", 3, 36)); // NOI18N
        lblTituloPersonajeDetalle.setForeground(new java.awt.Color(51, 204, 255));
        lblTituloPersonajeDetalle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPersonajeDetalle.setText("Nuevo personaje");
        lblTituloPersonajeDetalle.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        panelDetallePersonaje.add(lblTituloPersonajeDetalle, gridBagConstraints);

        lblNombrePersonaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombrePersonaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombrePersonaje.setLabelFor(lblNombrePersonaje);
        lblNombrePersonaje.setText("Nombre:");
        lblNombrePersonaje.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblNombrePersonaje.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        lblNombrePersonaje.setMinimumSize(new java.awt.Dimension(100, 22));
        lblNombrePersonaje.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(lblNombrePersonaje, gridBagConstraints);

        txtNombrePersonaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombrePersonaje.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombrePersonaje.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        txtNombrePersonaje.setMinimumSize(new java.awt.Dimension(100, 22));
        txtNombrePersonaje.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(txtNombrePersonaje, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Apodo:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 22));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Avatar:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 22));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Elemento");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 22));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Creador:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 22));
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tipo:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jLabel6.setMinimumSize(new java.awt.Dimension(100, 22));
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(jLabel6, gridBagConstraints);

        txtApodoPersonaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApodoPersonaje.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApodoPersonaje.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        txtApodoPersonaje.setMinimumSize(new java.awt.Dimension(100, 22));
        txtApodoPersonaje.setPreferredSize(new java.awt.Dimension(100, 22));
        txtApodoPersonaje.addActionListener(this::txtApodoPersonajeActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(txtApodoPersonaje, gridBagConstraints);

        cbTipoElemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTipoElemento.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        cbTipoElemento.setMinimumSize(new java.awt.Dimension(100, 22));
        cbTipoElemento.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(cbTipoElemento, gridBagConstraints);

        cbTipoPersonaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTipoPersonaje.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        cbTipoPersonaje.setMinimumSize(new java.awt.Dimension(100, 22));
        cbTipoPersonaje.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(cbTipoPersonaje, gridBagConstraints);

        cbCreadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCreadores.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        cbCreadores.setMinimumSize(new java.awt.Dimension(100, 22));
        cbCreadores.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(cbCreadores, gridBagConstraints);

        jPanel1.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 22));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Sin avatar");
        jLabel9.setMaximumSize(new java.awt.Dimension(80, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(jLabel9);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Añadir");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetallePersonaje.add(jPanel1, gridBagConstraints);

        btnAddPersonaje.setText("Añadir personaje");
        btnAddPersonaje.setToolTipText("");
        btnAddPersonaje.addActionListener(this::btnAddPersonajeActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelDetallePersonaje.add(btnAddPersonaje, gridBagConstraints);

        panelFormulario.add(panelDetallePersonaje);

        panelDetalleCreador.setBackground(new java.awt.Color(102, 102, 102));
        panelDetalleCreador.setPreferredSize(new java.awt.Dimension(527, 100));
        panelDetalleCreador.setLayout(new java.awt.GridBagLayout());

        lblTituloPersonajeDetalle1.setBackground(new java.awt.Color(51, 0, 204));
        lblTituloPersonajeDetalle1.setFont(new java.awt.Font("Yu Gothic", 3, 36)); // NOI18N
        lblTituloPersonajeDetalle1.setForeground(new java.awt.Color(51, 204, 255));
        lblTituloPersonajeDetalle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPersonajeDetalle1.setText("Creador");
        lblTituloPersonajeDetalle1.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        panelDetalleCreador.add(lblTituloPersonajeDetalle1, gridBagConstraints);

        lblNombrePersonaje1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombrePersonaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombrePersonaje1.setLabelFor(lblNombrePersonaje);
        lblNombrePersonaje1.setText("Nombre:");
        lblNombrePersonaje1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblNombrePersonaje1.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        lblNombrePersonaje1.setMinimumSize(new java.awt.Dimension(100, 22));
        lblNombrePersonaje1.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetalleCreador.add(lblNombrePersonaje1, gridBagConstraints);

        txtNombreCreador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreCreador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreCreador.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        txtNombreCreador.setMinimumSize(new java.awt.Dimension(100, 22));
        txtNombreCreador.setPreferredSize(new java.awt.Dimension(100, 22));
        txtNombreCreador.addActionListener(this::txtNombreCreadorActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetalleCreador.add(txtNombreCreador, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Apellidos:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel10.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jLabel10.setMinimumSize(new java.awt.Dimension(100, 22));
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetalleCreador.add(jLabel10, gridBagConstraints);

        txtApellidosCreador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidosCreador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellidosCreador.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        txtApellidosCreador.setMinimumSize(new java.awt.Dimension(100, 22));
        txtApellidosCreador.setPreferredSize(new java.awt.Dimension(100, 22));
        txtApellidosCreador.addActionListener(this::txtApellidosCreadorActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetalleCreador.add(txtApellidosCreador, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ID Creador:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelDetalleCreador.add(jLabel1, gridBagConstraints);

        txtIdCreador.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDetalleCreador.add(txtIdCreador, gridBagConstraints);

        btnAddCreador.setText("Agregar creador");
        btnAddCreador.addActionListener(this::btnAddCreadorActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelDetalleCreador.add(btnAddCreador, gridBagConstraints);

        panelFormulario.add(panelDetalleCreador);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(panelFormulario, gridBagConstraints);

        scrollPanelListaPersonajes.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre personaje", "Apodo", "Tipo", "Elemento", "Creador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPanelListaPersonajes.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(scrollPanelListaPersonajes, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtApodoPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApodoPersonajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApodoPersonajeActionPerformed

    private void txtNombreCreadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCreadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCreadorActionPerformed

    private void txtApellidosCreadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosCreadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosCreadorActionPerformed

    private void btnAddCreadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCreadorActionPerformed
        //Validar info
        if (txtNombreCreador.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Nombre no puede estar vacío");
            return;
        }
        if (txtApellidosCreador.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo apellidos no puede estar vacío");
            return;
        }

        Creador nuevoCreador = new Creador(txtNombreCreador.getText(), txtApellidosCreador.getText());
        creadores.add(nuevoCreador);
        cbCreadores.addItem(nuevoCreador);
        txtIdCreador.setText(String.valueOf(Creador.getSiguienteId()));

        //Limpiar campos de texto
        txtApellidosCreador.setText("");
        txtNombreCreador.setText("");

        JOptionPane.showMessageDialog(this, "Creador agregado correctamente");
    }//GEN-LAST:event_btnAddCreadorActionPerformed

    private void btnAddPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonajeActionPerformed
        if (cbTipoElemento.getSelectedItem() == Elemento.SELECCIONAR) {
            JOptionPane.showMessageDialog(this, "Selecciona un elemento");
            return;
        }
        if (cbTipoPersonaje.getSelectedItem() == TipoPersonaje.SELECCIONAR) {
            JOptionPane.showMessageDialog(this, "Selecciona un tipo de personaje");
            return;
        }
        if (cbCreadores.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un creador");
            return;
        }

        if (txtNombrePersonaje.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Nombre no puede estar vacío");
            return;
        }

        if (txtApodoPersonaje.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Apodo no puede estar vacío");
            return;
        }
        Creador creadorDelPersonaje = (Creador) cbCreadores.getSelectedItem();

        Personaje nuevoPersonaje = new Personaje(
                txtNombrePersonaje.getText(),
                (Elemento) cbTipoElemento.getSelectedItem(),
                "sfds",
                txtApodoPersonaje.getText(),
                (TipoPersonaje) cbTipoPersonaje.getSelectedItem(),
                creadorDelPersonaje.getIdCreador());

        personajes.add(nuevoPersonaje);

        txtNombrePersonaje.setText("");
        txtApodoPersonaje.setText("");
        cbCreadores.setSelectedIndex(0);
        cbTipoElemento.setSelectedIndex(0);
        cbTipoPersonaje.setSelectedIndex(0);

        cargarPersonajes();
        JOptionPane.showMessageDialog(this, "Personaje agregado correctamente");

    }//GEN-LAST:event_btnAddPersonajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdministradorPersonajes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCreador;
    private javax.swing.JButton btnAddPersonaje;
    private javax.swing.JComboBox<Creador> cbCreadores;
    private javax.swing.JComboBox<Elemento> cbTipoElemento;
    private javax.swing.JComboBox<TipoPersonaje> cbTipoPersonaje;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNombrePersonaje;
    private javax.swing.JLabel lblNombrePersonaje1;
    private javax.swing.JLabel lblTituloPersonajeDetalle;
    private javax.swing.JLabel lblTituloPersonajeDetalle1;
    private javax.swing.JPanel panelDetalleCreador;
    private javax.swing.JPanel panelDetallePersonaje;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JScrollPane scrollPanelListaPersonajes;
    private javax.swing.JTextField txtApellidosCreador;
    private javax.swing.JTextField txtApodoPersonaje;
    private javax.swing.JTextField txtIdCreador;
    private javax.swing.JTextField txtNombreCreador;
    private javax.swing.JTextField txtNombrePersonaje;
    // End of variables declaration//GEN-END:variables
}
