/*


 */
package sesion44;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tl
 */
public class App extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(App.class.getName());
    private AlumnoCRUD alumnoCRUD;

    /**
     * Creates new form App
     */
    public App() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        paneDashboard = new javax.swing.JPanel();
        lblEstadoConexion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDashboard = new javax.swing.JTable();
        btnConectarDB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCargarAlumnos = new javax.swing.JButton();
        paneActualizar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNombreActualizar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtApellidoActualizar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCredencialActualizar = new javax.swing.JTextField();
        btnActualizarAlumno = new javax.swing.JButton();
        cbCarreraActualizar = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEdadActualizar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdAlumnoActualizar = new javax.swing.JTextField();
        btnObtenerAlumnoActuallizar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtidAlumnoActualizar1 = new javax.swing.JTextField();
        paneEliminar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtIdAlumnoEliminar = new javax.swing.JTextField();
        btnEliminarAlumno = new javax.swing.JButton();
        paneCrear = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreCrear = new javax.swing.JTextField();
        txtApellidoCrear = new javax.swing.JTextField();
        txtEdadCrear = new javax.swing.JTextField();
        txtCredencialCrear = new javax.swing.JTextField();
        btnCrearAlumno = new javax.swing.JButton();
        cbCarreraCrear = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escuela NO. 127");
        jLabel1.setAlignmentX(0.5F);
        getContentPane().add(jLabel1);

        lblEstadoConexion.setForeground(new java.awt.Color(255, 0, 0));
        lblEstadoConexion.setText("Desconectado");

        tblDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Edad", "Carrera", "Credencial"
            }
        ));
        jScrollPane1.setViewportView(tblDashboard);

        btnConectarDB.setText("Conectar");
        btnConectarDB.addActionListener(this::btnConectarDBActionPerformed);

        jLabel2.setText("Estado: ");

        btnCargarAlumnos.setText("Cargar alumnos");
        btnCargarAlumnos.addActionListener(this::btnCargarAlumnosActionPerformed);

        javax.swing.GroupLayout paneDashboardLayout = new javax.swing.GroupLayout(paneDashboard);
        paneDashboard.setLayout(paneDashboardLayout);
        paneDashboardLayout.setHorizontalGroup(
            paneDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDashboardLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(paneDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneDashboardLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstadoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(paneDashboardLayout.createSequentialGroup()
                            .addComponent(btnConectarDB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCargarAlumnos))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        paneDashboardLayout.setVerticalGroup(
            paneDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneDashboardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblEstadoConexion))
                .addGap(18, 18, 18)
                .addGroup(paneDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneDashboardLayout.createSequentialGroup()
                        .addComponent(btnConectarDB)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneDashboardLayout.createSequentialGroup()
                        .addComponent(btnCargarAlumnos)
                        .addGap(8, 8, 8)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dashboard", paneDashboard);

        jLabel9.setText("Nombre");

        jLabel10.setText("Apellido");

        jLabel11.setText("Credencial");

        btnActualizarAlumno.setText("Actualizar");
        btnActualizarAlumno.addActionListener(this::btnActualizarAlumnoActionPerformed);

        cbCarreraActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desarrollador de sistemas y redes", "Asistente ejecutivo", "Diseñador gráfico" }));

        jLabel12.setText("Carrera");

        jLabel13.setText("Edad");

        jLabel3.setText("ID de alumno a buscar");

        btnObtenerAlumnoActuallizar.setText("Buscar");
        btnObtenerAlumnoActuallizar.addActionListener(this::btnObtenerAlumnoActuallizarActionPerformed);

        jLabel14.setText("ID");

        txtidAlumnoActualizar1.setEnabled(false);

        javax.swing.GroupLayout paneActualizarLayout = new javax.swing.GroupLayout(paneActualizar);
        paneActualizar.setLayout(paneActualizarLayout);
        paneActualizarLayout.setHorizontalGroup(
            paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneActualizarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneActualizarLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtidAlumnoActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneActualizarLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCredencialActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarAlumno)
                            .addGroup(paneActualizarLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(cbCarreraActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneActualizarLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnObtenerAlumnoActuallizar)
                                    .addComponent(txtEdadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(paneActualizarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addComponent(txtIdAlumnoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneActualizarLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneActualizarLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        paneActualizarLayout.setVerticalGroup(
            paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneActualizarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdAlumnoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObtenerAlumnoActuallizar))
                .addGap(64, 64, 64)
                .addGroup(paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtidAlumnoActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(txtEdadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(cbCarreraActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtApellidoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(paneActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCredencialActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarAlumno))
                .addGap(18, 321, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actualizar alumno", paneActualizar);

        jLabel15.setText("ID de alumno a eliminar");

        btnEliminarAlumno.setText("Eliminar");
        btnEliminarAlumno.addActionListener(this::btnEliminarAlumnoActionPerformed);

        javax.swing.GroupLayout paneEliminarLayout = new javax.swing.GroupLayout(paneEliminar);
        paneEliminar.setLayout(paneEliminarLayout);
        paneEliminarLayout.setHorizontalGroup(
            paneEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
            .addGroup(paneEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneEliminarLayout.createSequentialGroup()
                    .addGap(241, 241, 241)
                    .addGroup(paneEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneEliminarLayout.createSequentialGroup()
                            .addGap(332, 332, 332)
                            .addComponent(btnEliminarAlumno))
                        .addGroup(paneEliminarLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(34, 34, 34)
                            .addComponent(txtIdAlumnoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(242, Short.MAX_VALUE)))
        );
        paneEliminarLayout.setVerticalGroup(
            paneEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
            .addGroup(paneEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneEliminarLayout.createSequentialGroup()
                    .addGap(283, 283, 283)
                    .addGroup(paneEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtIdAlumnoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarAlumno))
                    .addContainerGap(283, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Eliminar alumno", paneEliminar);

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Edad");

        jLabel7.setText("Carrera");

        jLabel8.setText("Credencial");

        btnCrearAlumno.setText("Guardar");
        btnCrearAlumno.addActionListener(this::btnCrearAlumnoActionPerformed);

        cbCarreraCrear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desarrollador de sistemas y redes", "Asistente ejecutivo", "Diseñador gráfico" }));

        javax.swing.GroupLayout paneCrearLayout = new javax.swing.GroupLayout(paneCrear);
        paneCrear.setLayout(paneCrearLayout);
        paneCrearLayout.setHorizontalGroup(
            paneCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCrearLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCrearLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCrearLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCrearLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCredencialCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(paneCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCrearLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(paneCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneCrearLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cbCarreraCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneCrearLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(30, 30, 30)
                                .addComponent(txtEdadCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(paneCrearLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnCrearAlumno)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        paneCrearLayout.setVerticalGroup(
            paneCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCrearLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(paneCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtEdadCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(paneCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(paneCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtApellidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(cbCarreraCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(paneCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCredencialCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearAlumno))
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear alumno", paneCrear);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Crear empleado\n");

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarDBActionPerformed
        alumnoCRUD = new AlumnoCRUD();
        if (alumnoCRUD.estaConectado()) {
            lblEstadoConexion.setText("Conectado");
            lblEstadoConexion.setForeground(Color.GREEN);
            JOptionPane.showMessageDialog(this, "✅ Conexión exitosa a MySQL", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            lblEstadoConexion.setText("Desconectado");
            lblEstadoConexion.setForeground(Color.RED);
            JOptionPane.showMessageDialog(this, "❌ Error de conexión", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConectarDBActionPerformed

    private void btnCargarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarAlumnosActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblDashboard.getModel();
        List<Object[]> alumnos = alumnoCRUD.obtenerAlumnos();

        model.setRowCount(0); // Limpiar datos
        for (Object[] fila : alumnos) {
            model.addRow(fila);
        }

        JOptionPane.showMessageDialog(this, "Alumnos cargados correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnCargarAlumnosActionPerformed

    private void btnCrearAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAlumnoActionPerformed
        String nombre = txtNombreCrear.getText();
        String apellido = txtApellidoCrear.getText();
        int edad = Integer.parseInt(txtEdadCrear.getText());
        String carrera = cbCarreraCrear.getSelectedItem().toString();
        int credencial = Integer.parseInt(txtCredencialCrear.getText().toString());
        boolean exito = alumnoCRUD.crearAlumno(nombre, apellido, edad, carrera, credencial);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Alumno agregado correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Algo salió mal. Intente otra vez.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCrearAlumnoActionPerformed

    private void btnActualizarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoActionPerformed
        int id = Integer.parseInt(txtidAlumnoActualizar1.getText());
        String nombre = txtNombreActualizar.getText();
        String apellido = txtApellidoActualizar.getText();
        int edad = Integer.parseInt(txtEdadActualizar.getText());
        String carrera = cbCarreraActualizar.getSelectedItem().toString();
        int credencial = Integer.parseInt(txtCredencialActualizar.getText());
        boolean exito = alumnoCRUD.actualizarAlumno(id, nombre, apellido, edad, carrera, credencial);

        if (exito) {
            txtApellidoActualizar.setText("");
            txtNombreActualizar.setText("");
            txtEdadActualizar.setText("");
            txtidAlumnoActualizar1.setText("");
            txtCredencialActualizar.setText("");
            JOptionPane.showMessageDialog(this, "Alumno actualizado correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Algo salió mal", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarAlumnoActionPerformed

    private void btnObtenerAlumnoActuallizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerAlumnoActuallizarActionPerformed
        int idAlumno = Integer.parseInt(txtIdAlumnoActualizar.getText());
        Object[] alumno = alumnoCRUD.obtenerAlumnoPorId(idAlumno);
        if (alumno != null) {
            txtidAlumnoActualizar1.setText(alumno[0].toString());
            txtNombreActualizar.setText(alumno[1].toString());
            txtApellidoActualizar.setText(alumno[2].toString());
            txtEdadActualizar.setText(alumno[3].toString());
            cbCarreraActualizar.setSelectedItem(alumno[4]);
            txtCredencialActualizar.setText(alumno[5].toString());

            JOptionPane.showMessageDialog(this, "Alumno cargado correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "No se encontró al alumno con el ID dado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObtenerAlumnoActuallizarActionPerformed

    private void btnEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoActionPerformed
        int idAlumno = Integer.parseInt(txtIdAlumnoEliminar.getText());
        Object[] alumno = alumnoCRUD.obtenerAlumnoPorId(idAlumno);
        if (alumno != null) {
            boolean exito = alumnoCRUD.eliminarAlumno(idAlumno);
            if (exito) {
                JOptionPane.showMessageDialog(this, "Alumno elimindo Correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Algo salió mal", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró al alumno con el ID dado", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEliminarAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new App().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarAlumno;
    private javax.swing.JButton btnCargarAlumnos;
    private javax.swing.JButton btnConectarDB;
    private javax.swing.JButton btnCrearAlumno;
    private javax.swing.JButton btnEliminarAlumno;
    private javax.swing.JButton btnObtenerAlumnoActuallizar;
    private javax.swing.JComboBox<String> cbCarreraActualizar;
    private javax.swing.JComboBox<String> cbCarreraCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEstadoConexion;
    private javax.swing.JPanel paneActualizar;
    private javax.swing.JPanel paneCrear;
    private javax.swing.JPanel paneDashboard;
    private javax.swing.JPanel paneEliminar;
    private javax.swing.JTable tblDashboard;
    private javax.swing.JTextField txtApellidoActualizar;
    private javax.swing.JTextField txtApellidoCrear;
    private javax.swing.JTextField txtCredencialActualizar;
    private javax.swing.JTextField txtCredencialCrear;
    private javax.swing.JTextField txtEdadActualizar;
    private javax.swing.JTextField txtEdadCrear;
    private javax.swing.JTextField txtIdAlumnoActualizar;
    private javax.swing.JTextField txtIdAlumnoEliminar;
    private javax.swing.JTextField txtNombreActualizar;
    private javax.swing.JTextField txtNombreCrear;
    private javax.swing.JTextField txtidAlumnoActualizar1;
    // End of variables declaration//GEN-END:variables
}
