/*


 */
package sesion11;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author tl
 */
public class TarjetaMago extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TarjetaMago.class.getName());

    /**
     * Creates new form TarjetaMago
     */
    public TarjetaMago(Mago mago) {
        setUndecorated(true); // Quitar decoración de windows
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30)); // Bordes redondeados
        setLocationRelativeTo(null);

        // Mostrar valores en tarjeta
        lblNombre.setText(mago.getNombre()); // nombre
        lblAvatar.setText(mago.getApodo()); // Alias
        lblHabilidadBasica.setText(mago.getHabilidadBasica()); // Habilidad básica
        lblDañoBasica.setText(mago.getDañoHabilidadBasica() + " pts"); // Daño (básica
        lblHabilidadEspecial.setText(mago.getHabilidadEspecial()); // Habilidad especial
        lblDañoEspecial.setText(mago.getDañoHabilidadEspecial() + " pts");
        
        lblPuntosDeVida.setText(mago.getPuntosDeVida() + " pts");
        
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesion11/avatars/" + mago.getRutaAvatar())));
        
        switch (mago.getTipo()) {
            case TipoMago.AGUA -> {
                lblTipo.setBackground(Color.BLUE);
                lblTipo.setForeground(new Color(0, 229, 255));
                lblTipo.setText(mago.getTipo());
            }
            case TipoMago.FUEGO -> {
                lblTipo.setBackground(Color.red);
                lblTipo.setForeground(new Color(255, 162, 162));
                lblTipo.setText(mago.getTipo());
            }
            case TipoMago.LUZ -> {
                lblTipo.setForeground(Color.orange);
                lblTipo.setBackground(new Color(238, 255, 151));
                lblTipo.setText(mago.getTipo());
            }
            case TipoMago.OSCURIDAD -> {
                lblTipo.setForeground(Color.GRAY);
                lblTipo.setBackground(Color.BLACK);
                lblTipo.setText(mago.getTipo());
                lblTipo.setMaximumSize(new Dimension(130, lblTipo.getSize().height));
            }
            default -> {
                lblTipo.setBackground(Color.GRAY);
                lblTipo.setForeground(Color.LIGHT_GRAY);
                lblTipo.setText("Desconocido");
                lblTipo.setMaximumSize(new Dimension(130, lblTipo.getSize().height));
            }
        }
        
    }
    
    public TarjetaMago() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        paneDetalle = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        lblNombre = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPuntosDeVida = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblHabilidadBasica = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDañoBasica = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblHabilidadEspecial = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDañoEspecial = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnCerrar = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        lblAvatar.setBackground(new java.awt.Color(0, 204, 153));
        lblAvatar.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        lblAvatar.setForeground(new java.awt.Color(255, 255, 255));
        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setText("vcxvxc");
        lblAvatar.setAlignmentX(0.5F);
        lblAvatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAvatar.setVerifyInputWhenFocusTarget(false);
        lblAvatar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(lblAvatar);

        getContentPane().add(jPanel3);

        paneDetalle.setBackground(new java.awt.Color(51, 51, 51));
        paneDetalle.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        paneDetalle.setLayout(new javax.swing.BoxLayout(paneDetalle, javax.swing.BoxLayout.Y_AXIS));
        paneDetalle.add(filler1);

        lblNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 204, 204));
        lblNombre.setText("Pan de Limon");
        lblNombre.setAlignmentX(0.5F);
        paneDetalle.add(lblNombre);

        lblTipo.setBackground(new java.awt.Color(255, 102, 102));
        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("jLabel5");
        lblTipo.setAlignmentX(0.5F);
        lblTipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTipo.setFocusable(false);
        lblTipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTipo.setIconTextGap(10);
        lblTipo.setMaximumSize(new java.awt.Dimension(100, 260));
        lblTipo.setMinimumSize(new java.awt.Dimension(70, 50));
        lblTipo.setOpaque(true);
        lblTipo.setPreferredSize(new java.awt.Dimension(70, 30));
        paneDetalle.add(lblTipo);
        paneDetalle.add(filler5);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(416, 200));
        jPanel2.setLayout(new java.awt.GridLayout(5, 2, 10, 0));

        jLabel3.setBackground(new java.awt.Color(51, 0, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setLabelFor(lblPuntosDeVida);
        jLabel3.setText("Puntos de vida: ");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3);

        lblPuntosDeVida.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblPuntosDeVida.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntosDeVida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPuntosDeVida.setText("100 pts");
        jPanel2.add(lblPuntosDeVida);

        jLabel5.setBackground(new java.awt.Color(51, 0, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setLabelFor(lblPuntosDeVida);
        jLabel5.setText("Habilidad (básica):");
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel5);

        lblHabilidadBasica.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblHabilidadBasica.setForeground(new java.awt.Color(255, 255, 255));
        lblHabilidadBasica.setText("habilidad ");
        lblHabilidadBasica.setAlignmentX(0.5F);
        lblHabilidadBasica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblHabilidadBasica);

        jLabel6.setBackground(new java.awt.Color(51, 0, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setLabelFor(lblPuntosDeVida);
        jLabel6.setText("Daño (básica):");
        jLabel6.setAlignmentX(0.5F);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel6);

        lblDañoBasica.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblDañoBasica.setForeground(new java.awt.Color(255, 255, 255));
        lblDañoBasica.setText("10 pts");
        lblDañoBasica.setAlignmentX(0.5F);
        lblDañoBasica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblDañoBasica);

        jLabel7.setBackground(new java.awt.Color(51, 0, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setLabelFor(lblPuntosDeVida);
        jLabel7.setText("Habilidad (especial):");
        jLabel7.setAlignmentX(0.5F);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel7);

        lblHabilidadEspecial.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblHabilidadEspecial.setForeground(new java.awt.Color(255, 255, 255));
        lblHabilidadEspecial.setText("habilidad ");
        lblHabilidadEspecial.setAlignmentX(0.5F);
        lblHabilidadEspecial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblHabilidadEspecial);

        jLabel8.setBackground(new java.awt.Color(51, 0, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setLabelFor(lblPuntosDeVida);
        jLabel8.setText("Daño (especial):");
        jLabel8.setAlignmentX(0.5F);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel8);

        lblDañoEspecial.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblDañoEspecial.setForeground(new java.awt.Color(255, 255, 255));
        lblDañoEspecial.setText("10 pts");
        lblDañoEspecial.setAlignmentX(0.5F);
        lblDañoEspecial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblDañoEspecial);

        paneDetalle.add(jPanel2);
        paneDetalle.add(filler2);

        btnCerrar.setBackground(new java.awt.Color(255, 51, 0));
        btnCerrar.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.setAlignmentX(0.5F);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setFocusable(false);
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);
        paneDetalle.add(btnCerrar);
        paneDetalle.add(filler7);

        getContentPane().add(paneDetalle);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0); // terminar el programa
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TarjetaMago().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblDañoBasica;
    private javax.swing.JLabel lblDañoEspecial;
    private javax.swing.JLabel lblHabilidadBasica;
    private javax.swing.JLabel lblHabilidadEspecial;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuntosDeVida;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel paneDetalle;
    // End of variables declaration//GEN-END:variables
}
