/*


 */
package sesion9;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.geom.RoundRectangle2D;
import java.net.URI;
import javax.swing.Timer;

/**
 *
 * @author tl
 */
public class TarjetaDePerfil extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TarjetaDePerfil.class.getName());
    private int indiceActual = 0; // modificación en lambda del timer
    private static final String[] frases = {
        "Cada línea de código te acerca a tu meta.",
        "Los errores también enseñan.",
        "No te rindas, depurar también es avanzar.",
        "Hoy puede ser el día de tu gran idea.",
        "La práctica convierte problemas en experiencia.",
        "Un pequeño avance sigue siendo avance.",
        "Tu disciplina vale más que la motivación.",
        "Todo proyecto grande comenzó vacío.",
        "Aprender programación es construir tu futuro.",
        "Confía en el proceso.",
        "Cada bug resuelto te hace mejor developer.",
        "Hazlo funcionar, luego hazlo bonito.",
        "La constancia supera al talento.",
        "Nunca subestimes un café y una buena idea.",
        "Tu código puede cambiar vidas.",
        "Lo difícil hoy será fácil mañana.",
        "Sigue creando.",
        "Todo experto alguna vez fue principiante.",
        "No pares hasta sentir orgullo de lo que hiciste.",
        "El éxito se compila paso a paso."
    };

    /**
     * Creates new form TarjetaDePerfil
     */
    public TarjetaDePerfil() {
        setUndecorated(true); // Quitar decoración nativa del sistema
        initComponents(); // Crea los elementos del designer
        getContentPane().setBackground(new Color(30, 30, 30));
        // Hace la ventana con esquinas redondeadas
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));

        setLocationRelativeTo(null);// Centra la ventana en la pantalla

        // Mostrar frases cada 3 segundos
        int total = frases.length; // total de frases
        pbFrases.setMinimum(0);
        pbFrases.setMaximum(total);

        // Primera vuelta antes del timer
        lblFraseAleatoria.setText(
                "<html>"
                + "<div style='padding:0;margin:auto;text-align:center; width: 250;'>\""
                + frases[indiceActual]
                + "\"</div>"
                + "</html>");
        lblFraseAleatoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pbFrases.setValue(indiceActual + 1);
        indiceActual++;

        Timer temporizador = new Timer(3000, e -> {
            // Al llegar al último elemento reiniciar
            if (indiceActual >= total) {
                indiceActual = 0;
            }

            lblFraseAleatoria.setText(
                    "<html>"
                    + "<div style='padding:0;margin:auto;text-align:center; width: 250;'>\""
                    + frases[indiceActual]
                    + "\"</div>"
                    + "</html>");

            // Asegurar texto centrado
            lblFraseAleatoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            // Actualizar barra de progreso
            pbFrases.setValue(indiceActual + 1);

            // Pasar al siguiente elemento en la siguiente vuelta
            indiceActual++;
        });

        temporizador.start(); // iniciar temporizador

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        paneDetalle = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel1 = new javax.swing.JLabel();
        btnUrl = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        lblFraseAleatoria = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        pbFrases = new javax.swing.JProgressBar();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jButton1 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        jRadioButton1.setText("jRadioButton1");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foto.png"))); // NOI18N

        paneDetalle.setBackground(new java.awt.Color(0, 0, 60));
        paneDetalle.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        paneDetalle.setLayout(new javax.swing.BoxLayout(paneDetalle, javax.swing.BoxLayout.Y_AXIS));
        paneDetalle.add(filler1);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Pan de Limon");
        jLabel1.setAlignmentX(0.5F);
        paneDetalle.add(jLabel1);

        btnUrl.setBackground(new java.awt.Color(51, 51, 51));
        btnUrl.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        btnUrl.setForeground(new java.awt.Color(204, 255, 255));
        btnUrl.setText("https://tl.is-a.dev");
        btnUrl.setAlignmentX(0.5F);
        btnUrl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUrl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUrl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUrl.addActionListener(this::btnUrlActionPerformed);
        paneDetalle.add(btnUrl);
        paneDetalle.add(filler5);

        jPanel2.setBackground(new java.awt.Color(0, 0, 60));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel2.setPreferredSize(new java.awt.Dimension(416, 40));

        jLabel3.setBackground(new java.awt.Color(51, 0, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("11 Seguidores");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("8 Siguiendo");
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4);

        paneDetalle.add(jPanel2);
        paneDetalle.add(filler6);

        lblFraseAleatoria.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        lblFraseAleatoria.setForeground(new java.awt.Color(255, 255, 255));
        lblFraseAleatoria.setText("jLabel5");
        lblFraseAleatoria.setAlignmentX(0.5F);
        lblFraseAleatoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFraseAleatoria.setMinimumSize(new java.awt.Dimension(50, 50));
        lblFraseAleatoria.setPreferredSize(new java.awt.Dimension(65, 60));
        paneDetalle.add(lblFraseAleatoria);
        paneDetalle.add(filler3);

        pbFrases.setForeground(new java.awt.Color(153, 0, 153));
        pbFrases.setValue(50);
        pbFrases.setPreferredSize(new java.awt.Dimension(146, 6));
        paneDetalle.add(pbFrases);
        paneDetalle.add(filler4);

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cerrar");
        jButton1.setAlignmentX(0.5F);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        paneDetalle.add(jButton1);
        paneDetalle.add(filler2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(paneDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0); // terminar el programa
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrlActionPerformed
        // TODO add your handling code here:
        String textoDelUrl = btnUrl.getText();
        try {
            Desktop.getDesktop().browse(new URI(textoDelUrl));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUrlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TarjetaDePerfil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUrl;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblFraseAleatoria;
    private javax.swing.JPanel paneDetalle;
    private javax.swing.JProgressBar pbFrases;
    // End of variables declaration//GEN-END:variables
}
